# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: FirstJob
    steps:
    - bash: echo Build / FirstJob
    - bash: echo $(PipelineLevelVariable)
    - bash: echo BuildNumber:$(Build.BuildNumber)
    - bash: echo BuildId:$(Build.BuildId)
    - bash: echo SourceBranchName:$(Build.SourceBranchName)
    - bash: echo SourcesDirectory:$(Build.SourcesDirectory)
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: echo DefaultWorkingDirectory:$(System.DefaultWorkingDirectory)
    - bash: ls -R $(System.DefaultWorkingDirectory)

    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          **/*.yaml
          **/*.tf
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
    - bash: echo ArtifactStagingDirectory:$(Build.ArtifactStagingDirectory)
    - bash: ls -R (Build.ArtifactStagingDirectory)


  # - job: SecondJob
  #   steps:
  #   - bash: echo build / SecondJob

# - stage: DevDeploy
#   dependsOn: Build
#   variables:
#     enviroment: DevDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(enviroment) / FirstJob

# - stage: QADeploy
#   dependsOn: Build
#   variables:
#     enviroment: QADeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(enviroment) / FirstJob

# - stage: ProdDeploy
#   dependsOn:
#   - DevDeploy
#   - QADeploy
#   variables:
#     enviroment: ProdDeploy
#   jobs:
#   - job: FirstJob
#     steps:
#     - bash: echo $(enviroment) / FirstJob
